wandb_version: 1

Adam.decouple_wd:
  desc: null
  value: true
Adam.eps:
  desc: null
  value: 1.0e-05
Adam.lr:
  desc: null
  value: 0.001
Adam.mom:
  desc: null
  value: 0.9
Adam.sqr_mom:
  desc: null
  value: 0.99
Adam.wd:
  desc: null
  value: 0.01
BaseLoss.__init__.args:
  desc: null
  value: []
BaseLoss.__init__.axis:
  desc: null
  value: -1
BaseLoss.__init__.flatten:
  desc: null
  value: true
BaseLoss.__init__.floatify:
  desc: null
  value: false
BaseLoss.__init__.is_2d:
  desc: null
  value: true
BaseLoss.__init__.kwargs:
  desc: null
  value: {}
BaseLoss.__init__.loss_cls:
  desc: null
  value: torch.nn.modules.loss.CrossEntropyLoss
CrossEntropyLossFlat.__init__.args:
  desc: null
  value: []
CrossEntropyLossFlat.__init__.axis:
  desc: null
  value: -1
CrossEntropyLossFlat.__init__.flatten:
  desc: null
  value: true
CrossEntropyLossFlat.__init__.floatify:
  desc: null
  value: false
CrossEntropyLossFlat.__init__.is_2d:
  desc: null
  value: true
CrossEntropyLossFlat.__init__.kwargs:
  desc: null
  value: {}
DataLoader.__init__.after_batch:
  desc: null
  value: 'Pipeline: ReadTabBatch'
DataLoader.__init__.after_item:
  desc: null
  value: 'Pipeline: '
DataLoader.__init__.after_iter:
  desc: null
  value: null
DataLoader.__init__.batch_size:
  desc: null
  value: null
DataLoader.__init__.before_batch:
  desc: null
  value: 'Pipeline: '
DataLoader.__init__.before_iter:
  desc: null
  value: null
DataLoader.__init__.bs:
  desc: null
  value: 64
DataLoader.__init__.device:
  desc: null
  value: cuda:0
DataLoader.__init__.drop_last:
  desc: null
  value: true
DataLoader.__init__.indexed:
  desc: null
  value: null
DataLoader.__init__.n:
  desc: null
  value: null
DataLoader.__init__.num_workers:
  desc: null
  value: 0
DataLoader.__init__.pin_memory:
  desc: null
  value: false
DataLoader.__init__.shuffle:
  desc: null
  value: true
DataLoader.__init__.timeout:
  desc: null
  value: 0
Learner.__init__.loss_func:
  desc: null
  value: null
Learner.__init__.lr:
  desc: null
  value: 0.001
Learner.__init__.metrics:
  desc: null
  value: fastai2.metrics.accuracy
Learner.__init__.model_dir:
  desc: null
  value: models
Learner.__init__.moms:
  desc: null
  value:
  - 0.95
  - 0.85
  - 0.95
Learner.__init__.path:
  desc: null
  value: null
Learner.__init__.splitter:
  desc: null
  value: fastai2.torch_core.trainable_params
Learner.__init__.train_bn:
  desc: null
  value: true
Learner.__init__.wd:
  desc: null
  value: null
Learner.__init__.wd_bn_bias:
  desc: null
  value: false
Learner.fit.lr:
  desc: null
  value: null
Learner.fit.n_epoch:
  desc: null
  value: 3
Learner.fit.reset_opt:
  desc: null
  value: false
Learner.fit.wd:
  desc: null
  value: null
Optimizer.__init__.train_bn:
  desc: null
  value: true
ProgressCallback:
  desc: null
  value: true
Recorder:
  desc: null
  value: true
TfmdDL.__init__.after_batch:
  desc: null
  value: '(#1) [ReadTabBatch: (object,object) -> encodes (object,object) -> decodes]'
TfmdDL.__init__.after_item:
  desc: null
  value: null
TfmdDL.__init__.after_iter:
  desc: null
  value: null
TfmdDL.__init__.batch_size:
  desc: null
  value: null
TfmdDL.__init__.before_batch:
  desc: null
  value: null
TfmdDL.__init__.before_iter:
  desc: null
  value: null
TfmdDL.__init__.bs:
  desc: null
  value: 64
TfmdDL.__init__.device:
  desc: null
  value: cuda:0
TfmdDL.__init__.do_setup:
  desc: null
  value: true
TfmdDL.__init__.drop_last:
  desc: null
  value: true
TfmdDL.__init__.indexed:
  desc: null
  value: null
TfmdDL.__init__.n:
  desc: null
  value: null
TfmdDL.__init__.num_workers:
  desc: null
  value: 0
TfmdDL.__init__.pin_memory:
  desc: null
  value: false
TfmdDL.__init__.shuffle:
  desc: null
  value: true
TfmdDL.__init__.timeout:
  desc: null
  value: 0
TfmdDL.__init__.verbose:
  desc: null
  value: false
TrainEvalCallback:
  desc: null
  value: true
WandbCallback:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    cli_version: 0.9.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
batch per epoch:
  desc: null
  value: 407
batch size:
  desc: null
  value: 64
device:
  desc: null
  value: cuda
dls.after_batch:
  desc: null
  value: 'Pipeline: ReadTabBatch'
dls.after_item:
  desc: null
  value: 'Pipeline: '
dls.before_batch:
  desc: null
  value: 'Pipeline: '
frozen:
  desc: null
  value: false
frozen idx:
  desc: null
  value: 0
loss function:
  desc: null
  value: FlattenedLoss of CrossEntropyLoss()
n_inp:
  desc: null
  value: 2
optimizer:
  desc: null
  value: Adam
tabular_learner.config:
  desc: null
  value: null
tabular_learner.emb_szs:
  desc: null
  value: null
tabular_learner.layers:
  desc: null
  value:
  - 200
  - 100
tabular_learner.loss_func:
  desc: null
  value: null
tabular_learner.lr:
  desc: null
  value: 0.001
tabular_learner.metrics:
  desc: null
  value: fastai2.metrics.accuracy
tabular_learner.model_dir:
  desc: null
  value: models
tabular_learner.moms:
  desc: null
  value:
  - 0.95
  - 0.85
  - 0.95
tabular_learner.n_out:
  desc: null
  value: null
tabular_learner.path:
  desc: null
  value: null
tabular_learner.splitter:
  desc: null
  value: fastai2.torch_core.trainable_params
tabular_learner.train_bn:
  desc: null
  value: true
tabular_learner.wd:
  desc: null
  value: null
tabular_learner.wd_bn_bias:
  desc: null
  value: false
tabular_learner.y_range:
  desc: null
  value: null
